$background = 0a0f0e
$onBackground = dce8e5
$surface = 0a0f0e
$surfaceDim = 0a0f0e
$surfaceBright = 242e2d
$surfaceContainerLowest = 000000
$surfaceContainerLow = 0e1514
$surfaceContainer = 131b1a
$surfaceContainerHigh = 192120
$surfaceContainerHighest = 1d2826
$onSurface = dce8e5
$surfaceVariant = 1d2826
$onSurfaceVariant = a2adab
$outline = 6d7876
$outlineVariant = 3f4a48
$inverseSurface = f6faf8
$inverseOnSurface = 515655
$shadow = 000000
$scrim = 000000
$surfaceTint = 9cd1ca
$primary = 9cd1ca
$primaryDim = 8ec3bc
$onPrimary = 0e4844
$primaryContainer = 265b56
$onPrimaryContainer = b8eee7
$inversePrimary = 346762
$primaryFixed = b7ede6
$primaryFixedDim = a9dfd8
$onPrimaryFixed = 0d4743
$onPrimaryFixedVariant = 30645f
$secondary = b1ccc8
$secondaryDim = a3beba
$onSecondary = 2c4542
$secondaryContainer = 27403d
$onSecondaryContainer = a9c5c1
$secondaryFixed = cce8e4
$secondaryFixedDim = bedad6
$onSecondaryFixed = 2b4441
$onSecondaryFixedVariant = 47605d
$tertiary = daf1ff
$tertiaryDim = b7e6ff
$onTertiary = 2e5e73
$tertiaryContainer = b7e6ff
$onTertiaryContainer = 25566a
$tertiaryFixed = b7e6ff
$tertiaryFixedDim = a9d8f1
$onTertiaryFixed = 0a4356
$onTertiaryFixedVariant = 305f74
$error = fa746f
$errorDim = c54d4a
$onError = 490006
$errorContainer = 871f21
$onErrorContainer = ff9993
$primaryPaletteKeyColor = 4d807b
$secondaryPaletteKeyColor = 627c79
$tertiaryPaletteKeyColor = 4f7d93
$neutralPaletteKeyColor = 737877
$neutralVariantPaletteKeyColor = 6e7977
$errorPaletteKeyColor = c84f4c
$primary_paletteKeyColor = 4d807b
$secondary_paletteKeyColor = 627c79
$tertiary_paletteKeyColor = 4f7d93
$neutral_paletteKeyColor = 737877
$neutral_variant_paletteKeyColor = 6e7977
$term0 = 343434
$term1 = 769e00
$term2 = 5ae2bc
$term3 = 84fcca
$term4 = 76b6b1
$term5 = 7aaee9
$term6 = 84d9c7
$term7 = cddcd2
$term8 = 9ba59e
$term9 = 85b900
$term10 = 49f7cb
$term11 = ceffe7
$term12 = a4c8c2
$term13 = a2c0f7
$term14 = 8cedd6
$term15 = ffffff
$rosewater = f1f3e5
$flamingo = e3e4c5
$pink = bae2ff
$mauve = 5ecfe5
$red = 8ab5ff
$maroon = abbef0
$peach = a9daac
$yellow = d4fae7
$green = 8ff2dc
$teal = 9feee5
$sky = 93eae6
$sapphire = 70d7d8
$blue = 56cdd7
$lavender = 85dae5
$klink = 00969a
$klinkSelection = 00969b
$kvisited = 008ca9
$kvisitedSelection = 008ca9
$knegative = 838f00
$knegativeSelection = 838f00
$kneutral = 34c359
$kneutralSelection = 34c359
$kpositive = 00bea7
$kpositiveSelection = 00bea7
$text = dce8e5
$subtext1 = a2adab
$subtext0 = 6d7876
$overlay2 = 5f6967
$overlay1 = 505958
$overlay0 = 434b49
$surface2 = 353d3b
$surface1 = 282e2d
$surface0 = 191f1d
$base = 0a0f0e
$mantle = 0a0f0e
$crust = 090e0d
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
