$background = faf9fe
$onBackground = 2f323a
$surface = faf9fe
$surfaceDim = d7dae4
$surfaceBright = faf9fe
$surfaceContainerLowest = ffffff
$surfaceContainerLow = f3f3fa
$surfaceContainer = ededf6
$surfaceContainerHigh = e6e8f1
$surfaceContainerHighest = e0e2ed
$onSurface = 2f323a
$surfaceVariant = e0e2ed
$onSurfaceVariant = 5c5f68
$outline = 787a84
$outlineVariant = afb2bc
$inverseSurface = 0d0e12
$inverseOnSurface = 9c9ca2
$shadow = 000000
$scrim = 000000
$surfaceTint = 475f8b
$primary = 475f8b
$primaryDim = 3b537e
$onPrimary = f9f8ff
$primaryContainer = b4ccfe
$onPrimaryContainer = 2b446d
$inversePrimary = b4ccfe
$primaryFixed = b4ccfe
$primaryFixedDim = a7bff0
$onPrimaryFixed = 153058
$onPrimaryFixedVariant = 354d77
$secondary = 575f72
$secondaryDim = 4b5365
$onSecondary = f9f8ff
$secondaryContainer = dae2f9
$onSecondaryContainer = 495264
$secondaryFixed = dae2f9
$secondaryFixedDim = ccd4ea
$onSecondaryFixed = 373f51
$onSecondaryFixedVariant = 535c6e
$tertiary = 675881
$tertiaryDim = 5b4c75
$onTertiary = fef7ff
$tertiaryContainer = e0ccfd
$onTertiaryContainer = 51426a
$tertiaryFixed = e0ccfd
$tertiaryFixedDim = d1beee
$onTertiaryFixed = 3d2f56
$onTertiaryFixedVariant = 5a4b74
$error = a83836
$errorDim = 67040d
$onError = fff7f6
$errorContainer = fa746f
$onErrorContainer = 6e0a12
$primaryPaletteKeyColor = 5f77a4
$secondaryPaletteKeyColor = 6f778b
$tertiaryPaletteKeyColor = 806f9b
$neutralPaletteKeyColor = 76777c
$neutralVariantPaletteKeyColor = 747780
$errorPaletteKeyColor = c84f4c
$primary_paletteKeyColor = 5f77a4
$secondary_paletteKeyColor = 6f778b
$tertiary_paletteKeyColor = 806f9b
$neutral_paletteKeyColor = 76777c
$neutral_variant_paletteKeyColor = 747780
$term0 = 9a9b9b
$term1 = 484ae4
$term2 = 008ab8
$term3 = 7e61b0
$term4 = 009993
$term5 = 4b5ed5
$term6 = 4f84b9
$term7 = 212225
$term8 = 0f0f0f
$term9 = 6164fd
$term10 = 25ace1
$term11 = 9a7cce
$term12 = 3fbdb6
$term13 = 677af1
$term14 = 70a4dc
$term15 = 28282c
$rosewater = 7d76b1
$flamingo = 6f6dbc
$pink = 5f72ea
$mauve = 004ac5
$red = 371dff
$maroon = 5149f7
$peach = 8a4dff
$yellow = ac62b4
$green = 0076a7
$teal = 326ca0
$sky = 2e7bd0
$sapphire = 3a76b1
$blue = 0056b6
$lavender = 2a6eda
$klink = 5788ce
$klinkSelection = 5788ce
$kvisited = 617add
$kvisitedSelection = 607add
$knegative = 7a77ff
$knegativeSelection = 7a77ff
$kneutral = c794ff
$kneutralSelection = c794ff
$kpositive = 1db3ff
$kpositiveSelection = 1bb3ff
$text = 2f323a
$subtext1 = 5c5f68
$subtext0 = 787a84
$overlay2 = 888993
$overlay1 = 999ba3
$overlay0 = ababb3
$surface2 = bcbdc4
$surface1 = cfcfd6
$surface0 = e5e4ea
$base = faf9fe
$mantle = f2f1f5
$crust = ecebef
$success = 4F6354
$onSuccess = FFFFFF
$successContainer = D1E8D5
$onSuccessContainer = 0C1F13
