$background = 0b0f0c
$onBackground = dfe8dd
$surface = 0b0f0c
$surfaceDim = 0b0f0c
$surfaceBright = 262e27
$surfaceContainerLowest = 000000
$surfaceContainerLow = 101510
$surfaceContainer = 151b16
$surfaceContainerHigh = 1b211b
$surfaceContainerHighest = 202821
$onSurface = dfe8dd
$surfaceVariant = 202821
$onSurfaceVariant = a5ada3
$outline = 6f786f
$outlineVariant = 424a42
$inverseSurface = f7faf4
$inverseOnSurface = 525651
$shadow = 000000
$scrim = 000000
$surfaceTint = a8d0ae
$primary = a8d0ae
$primaryDim = 9bc2a0
$onPrimary = 24472e
$primaryContainer = 375a3f
$onPrimaryContainer = c5edc9
$inversePrimary = 43674b
$primaryFixed = c4edc9
$primaryFixedDim = b6debb
$onPrimaryFixed = 24472d
$onPrimaryFixedVariant = 406347
$secondary = b7ccb7
$secondaryDim = a9beaa
$onSecondary = 324535
$secondaryContainer = 2d4031
$onSecondaryContainer = b0c5b0
$secondaryFixed = d3e8d3
$secondaryFixedDim = c5dac5
$onSecondaryFixed = 314434
$onSecondaryFixedVariant = 4d604f
$tertiary = f4ffc6
$tertiaryDim = dce9aa
$onTertiary = 596432
$tertiaryContainer = e5f1b2
$onTertiaryContainer = 515b2b
$tertiaryFixed = f0fdbd
$tertiaryFixedDim = e2eeaf
$onTertiaryFixed = 465020
$onTertiaryFixedVariant = 626d3a
$error = fa746f
$errorDim = c54d4a
$onError = 490006
$errorContainer = 871f21
$onErrorContainer = ff9993
$primaryPaletteKeyColor = 5b8062
$secondaryPaletteKeyColor = 687c6a
$tertiaryPaletteKeyColor = 717c48
$neutralPaletteKeyColor = 747873
$neutralVariantPaletteKeyColor = 717970
$errorPaletteKeyColor = c84f4c
$primary_paletteKeyColor = 5b8062
$secondary_paletteKeyColor = 687c6a
$tertiary_paletteKeyColor = 717c48
$neutral_paletteKeyColor = 747873
$neutral_variant_paletteKeyColor = 717970
$term0 = 343433
$term1 = 769e00
$term2 = 91de8a
$term3 = b7f797
$term4 = 80b698
$term5 = c6a844
$term6 = 9ad7a4
$term7 = d3dbc9
$term8 = 9fa597
$term9 = 85b900
$term10 = 95f390
$term11 = daffc5
$term12 = aac8b1
$term13 = cec06b
$term14 = a8ebaf
$term15 = ffffff
$rosewater = f1f3e5
$flamingo = e3e4c5
$pink = ffd79d
$mauve = 5bd0df
$red = c5b542
$maroon = c6c177
$peach = bad79a
$yellow = e1f8d3
$green = aaf0b5
$teal = aeeec5
$sky = a0ebc5
$sapphire = 80d8b4
$blue = 63cfb2
$lavender = 89dcc7
$klink = 169979
$klinkSelection = 199977
$kvisited = 008ca9
$kvisitedSelection = 008ca9
$knegative = 838f00
$knegativeSelection = 838f00
$kneutral = 77bd2d
$kneutralSelection = 79bc2a
$kpositive = 3ec070
$kpositiveSelection = 41bf6e
$text = dfe8dd
$subtext1 = a5ada3
$subtext0 = 6f786f
$overlay2 = 616961
$overlay1 = 525952
$overlay0 = 444b45
$surface2 = 373d37
$surface1 = 292e2a
$surface0 = 1a1f1b
$base = 0b0f0c
$mantle = 0b0f0c
$crust = 0a0e0b
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
